config/routes.rb
ECloudsV01::Application.routes.draw do

  match "executions/costs" => "executions#costs" , :as => "costs"

  resources :executions do
    resources :jobs
  end

  resources :inputs

  resources :parameters

  resources :applications  do
    resources :inputs
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :virtual_machine_events

  resources :directories
  resources :cloud_files
  resources :instance_types
  resources :operating_systems
  resources :virtual_machines
  resources :clusters  do
    resources :virtual_machines
    member do
      post :add_virtual_machines
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :sessions => "sessions"}

  devise_scope :user do
    delete "users/sign_out"  => "devise/session#destroy"
  end

  root :to => "static_pages#home"

  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  get "browser/index"
  get "executions/costs"

  match "browse/index" => "browser#index" , :as =>  "data_home"

  match "browse/:directory_id" => "browser#browse", :as => "browse"
  match "browse/:directory_id/new_folder" => "directories#new", :as => "new_sub_directory"

  match "browse/:directory_id/new_file" => "cloud_files#new", :as => "new_sub_file"

  match "browse/:directory_id/rename" => "directories#edit", :as => "rename_directory"

  match "virtual_machines/:virtual_machine_id/stop/:current_cluster_id"  => "virtual_machines#stop", :as => "stop_virtual_machine"
  match "virtual_machines/:virtual_machine_id/start/:current_cluster_id"  => "virtual_machines#start", :as => "start_virtual_machine"
  match "virtual_machines/:virtual_machine_id/reboot/:current_cluster_id"  => "virtual_machines#reboot", :as => "reboot_virtual_machine"
  match "virtual_machines/:virtual_machine_id/terminate/:current_cluster_id"  => "virtual_machines#terminate", :as => "terminate_virtual_machine"

  match "virtual_machines/start_all/:current_cluster_id"  => "virtual_machines#start_all", :as => "start_all_virtual_machine"
  match "virtual_machines/reboot_all/:current_cluster_id"  => "virtual_machines#reboot_all", :as => "reboot_all_virtual_machine"
  match "virtual_machines/stop_all/:current_cluster_id"  => "virtual_machines#stop_all", :as => "stop_all_virtual_machine"
  match "virtual_machines/terminate_all/:current_cluster_id"  => "virtual_machines#terminate_all", :as => "terminate_all_virtual_machine"

  match "add_inputs/:application_id/" => "applications#add_inputs", :as => "add_inputs"
  match "organize_parameters/:application_id/" => "applications#organize_parameters", :as => "organize_parameters"
  match "decrease_position/:application_id/:input_id" => "applications#decrease_position_parameter" , :as => "decrease_position_parameter"
  match "increase_position/:application_id/:input_id" => "applications#increase_position_parameter" , :as => "increase_position_parameter"

  match "define_execution/:execution_id" => "executions#define_execution" , :as => "define_execution"
  match "define_execution_part2/:execution_id" => "executions#define_execution_part2" , :as => "define_execution_part2"
  match "launch_executions/:id" => "executions#launch_execution" , :as => "launch_execution"
  match "demo_executions/:application_id" => "executions#demo_execution" , :as => "demo_execution"

end

app/models/cluster.rb
class Cluster < ActiveRecord::Base
  attr_accessible :name , :instance_type, :user_id, :execution_id


  has_many :virtual_machines ,:dependent => :destroy
  has_many :jobs

  belongs_to :user
  belongs_to :execution


end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  # GET /clusters
  # GET /clusters.json
  def index



    @clusters = Cluster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clusters }
    end
  end

  # GET /clusters/1
  # GET /clusters/1.json
  def show

    @cluster = Cluster.find(params[:id])

    #ClustersHelper.current_cluster=(@cluster)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cluster }
    end
  end

  # GET /clusters/new
  # GET /clusters/new.json
  def new
    @cluster = Cluster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cluster }
    end
  end

  # GET /clusters/1/edit
  def edit
    @cluster = Cluster.find(params[:id])
  end

  # POST /clusters
  # POST /clusters.json
  def create
    @cluster = Cluster.new(params[:cluster])
    @cluster.user_id = current_user.id

    respond_to do |format|
      if @cluster.save
        format.html { redirect_to @cluster, notice: 'Cluster was successfully created.' }
        format.json { render json: @cluster, status: :created, location: @cluster }
      else
        format.html { render action: "new" }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clusters/1
  # PUT /clusters/1.json
  def update
    @cluster = Cluster.find(params[:id])

    respond_to do |format|
      if @cluster.update_attributes(params[:cluster])
        format.html { redirect_to @cluster, notice: 'Cluster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clusters/1
  # DELETE /clusters/1.json
  def destroy
    @cluster = Cluster.find(params[:id])
    @cluster.destroy
    @cluster.virtual_machines.destroy

    respond_to do |format|
      format.html { redirect_to clusters_url }
      format.json { head :no_content }
    end
  end

  def add_virtual_machines

    @ec2 = Aws::Ec2.new(AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY)

    @cluster = Cluster.find(params[:id])
    @number_of_vms = params["vms_number_input" ]
    @number_of_vms = @number_of_vms[:vm_number].to_i
    #@number_of_vms =5


    @instance_type = @cluster.instance_type
    #puts "hola!!!!!!!"
    #puts @cluster.name
    #puts @number_of_vms

       # falta coger info dependiendo del tipo de vm
    for i  in 1..@number_of_vms

      @instances = @ec2.launch_instances( ENV["AMI_APP_CIENTIFICAS_NAME"] ,:group_ids => [ENV["SECURITY_GROUP"]],
                                          :instance_type => @instance_type ,
                                          :user_data => 'EClouds Instance',
                                          :key_name => ENV["KEY_PAIR_NAME"])
      @instance = @instances[0]

      #@name =  (0..4).map{(65.+rand(25)).chr}.join
      @name = @instance[:aws_instance_id]

      @virtual_machine = VirtualMachine.new
      @virtual_machine.AMI_name = @name
      @virtual_machine.hostname = 'pending'
      puts 'obteniendo nombre de la vm'
      puts @virtual_machine.AMI_name
      @virtual_machine.slots = 1

      ## acá cojo el estado de la mv

      @virtual_machine.cluster_id = @cluster.id

      puts @virtual_machine.cluster_id
      @virtual_machine.save

      @event = VirtualMachineEvent.new

      @event.action = VIRTUAL_MACHINE_EVENTS[:CREATED]
      @event.vm_id = @virtual_machine.id
      @event.user_id = current_user.id
      @event.save

    end
      respond_to do |format|
       format.html { redirect_to @cluster, notice: 'Cluster was successfully updated.' }
       end
  end



end

app/helpers/clusters_helper.rb
module ClustersHelper

  def current_cluster=(cluster)
    @current_cluster = cluster
  end

end

app/views/clusters/_form.html.erb
<%= form_for(@cluster) do |f| %>
  <% if @cluster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cluster.errors.count, "error") %> prohibited this cluster from being saved:</h2>

      <ul>
      <% @cluster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>

    <%= f.label :instance_type_id %><br />
    <%= select :cluster,  :instance_type ,  Aws::Ec2::INSTANCE_TYPES  %><br />


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clusters/edit.html.erb
<h1>Editing cluster</h1>

<%= render 'form' %>

<%= link_to 'Show', @cluster %> |
<%= link_to 'Back', clusters_path %>

app/views/clusters/index.html.erb
<div class = "row">
  <div class="span8 label label-info">
    Listing clusters
  </div>

  <div class="span1">

  </div>

  <div class="span3">
    <%= link_to 'New Cluster', new_cluster_path %>

  </div>
</div>

<br>
<br>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% current_user.clusters.each do |cluster| %>
  <tr>
    <td><%= cluster.name %></td>
    <td><%= link_to 'Show', cluster %></td>
    <td><%= link_to 'Edit', edit_cluster_path(cluster) %></td>
    <td><%= link_to 'Destroy', cluster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/clusters/new.html.erb
<h1>New cluster</h1>

<%= render 'form' %>

<%= link_to 'Back', clusters_path %>

app/views/clusters/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<br>
<br>
<br>
<p>
  <b>Name:</b>
  <%= @cluster.name %>
  <br>
  <br>
  <b>InstanceType:</b>
  <%= @cluster.instance_type %>
</p>


<%= link_to 'Edit', edit_cluster_path(@cluster) %> |
<%= link_to 'Back', clusters_path %>

<br>
<div class="span4">
  <br>
  <h2> Add Virtual Machines</h2>
<%=  form_tag ( {:action => "add_virtual_machines" } ) do %>
    <table class="table">

      <tr>
        <td> Number of Instances:</td>
        <td> <%= select "vms_number_input", :vm_number, (1..5).map { |i| i} %>  </td>
        <td><%= submit_tag("Add")%></td>
      </tr>
    </table>
<% end %>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



<% if @cluster.virtual_machines.any? %>

    <button class="btn btn-info">
      <%= link_to 'Start All', start_all_virtual_machine_path( @cluster)%>
    </button>

    <button class="btn btn-info">
      <%= link_to 'Reboot All', reboot_all_virtual_machine_path( @cluster)%>
    </button>

    <button class="btn btn-info">
      <%= link_to 'Stop All', stop_all_virtual_machine_path( @cluster)%>
    </button>

    <button class="btn btn-info">
      <%= link_to 'Terminate All', terminate_all_virtual_machine_path( @cluster)%>
    </button>

    <br>
    <br>

<h3>Virtual Machines (<%= @cluster.virtual_machines.count %>)</h3>
<table class="table">
     <tr>
       <th>
         provider id
       </th>
         <th>
            internal dns Name
         </th>
         <th>
            State
         </th>
         <th>
            Slots
         </th>
         <th>
            Jobs
         </th>
     </tr>
  <% @cluster.virtual_machines.each do |virtual_machine| %>

      <% if !(virtual_machine.current_state == "terminated" ) %>

         <tr>
           <td><%= virtual_machine.AMI_name %></td>
            <td><%= virtual_machine.hostname %></td>
            <td><%= virtual_machine.current_state %></td>
            <td><%= virtual_machine.slots %></td>
            <td>
                <% virtual_machine.jobs.each do |job| %>
                  <%= link_to job.id, job %>
                <% end %>
              </td>

            <td><i class="icon-play-circle"></i><%= link_to 'Start', start_virtual_machine_path(virtual_machine, @cluster)%></td>
            <td><i class="icon-minus-sign"></i><%= link_to 'Stop', stop_virtual_machine_path(virtual_machine, @cluster)%></td>
            <td><i class="icon-repeat"></i><%= link_to 'Reboot', reboot_virtual_machine_path(virtual_machine, @cluster)%></td>
            <td><i class="icon-remove-sign"></i><%= link_to 'Terminate', terminate_virtual_machine_path(virtual_machine, @cluster)%></td>
     </tr>
      <% end %>
  <% end %>

</table>

<% end %>