config/routes.rb
ECloudsV01::Application.routes.draw do

  match "executions/costs" => "executions#costs" , :as => "costs"

  resources :executions do
    resources :jobs
  end

  resources :inputs

  resources :parameters

  resources :applications  do
    resources :inputs
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :virtual_machine_events

  resources :directories
  resources :cloud_files
  resources :instance_types
  resources :operating_systems
  resources :virtual_machines
  resources :clusters  do
    resources :virtual_machines
    member do
      post :add_virtual_machines
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :sessions => "sessions"}

  devise_scope :user do
    delete "users/sign_out"  => "devise/session#destroy"
  end

  root :to => "static_pages#home"

  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  get "browser/index"
  get "executions/costs"

  match "browse/index" => "browser#index" , :as =>  "data_home"

  match "browse/:directory_id" => "browser#browse", :as => "browse"
  match "browse/:directory_id/new_folder" => "directories#new", :as => "new_sub_directory"

  match "browse/:directory_id/new_file" => "cloud_files#new", :as => "new_sub_file"

  match "browse/:directory_id/rename" => "directories#edit", :as => "rename_directory"

  match "virtual_machines/:virtual_machine_id/stop/:current_cluster_id"  => "virtual_machines#stop", :as => "stop_virtual_machine"
  match "virtual_machines/:virtual_machine_id/start/:current_cluster_id"  => "virtual_machines#start", :as => "start_virtual_machine"
  match "virtual_machines/:virtual_machine_id/reboot/:current_cluster_id"  => "virtual_machines#reboot", :as => "reboot_virtual_machine"
  match "virtual_machines/:virtual_machine_id/terminate/:current_cluster_id"  => "virtual_machines#terminate", :as => "terminate_virtual_machine"

  match "virtual_machines/start_all/:current_cluster_id"  => "virtual_machines#start_all", :as => "start_all_virtual_machine"
  match "virtual_machines/reboot_all/:current_cluster_id"  => "virtual_machines#reboot_all", :as => "reboot_all_virtual_machine"
  match "virtual_machines/stop_all/:current_cluster_id"  => "virtual_machines#stop_all", :as => "stop_all_virtual_machine"
  match "virtual_machines/terminate_all/:current_cluster_id"  => "virtual_machines#terminate_all", :as => "terminate_all_virtual_machine"

  match "add_inputs/:application_id/" => "applications#add_inputs", :as => "add_inputs"
  match "organize_parameters/:application_id/" => "applications#organize_parameters", :as => "organize_parameters"
  match "decrease_position/:application_id/:input_id" => "applications#decrease_position_parameter" , :as => "decrease_position_parameter"
  match "increase_position/:application_id/:input_id" => "applications#increase_position_parameter" , :as => "increase_position_parameter"

  match "define_execution/:execution_id" => "executions#define_execution" , :as => "define_execution"
  match "define_execution_part2/:execution_id" => "executions#define_execution_part2" , :as => "define_execution_part2"
  match "launch_executions/:id" => "executions#launch_execution" , :as => "launch_execution"
  match "demo_executions/:application_id" => "executions#demo_execution" , :as => "demo_execution"

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :installer_url, :name, :version, :image ,:begin_command, :base_command, :end_command, :description, :vm_type, :estimated_time
  validates :installer_url, :presence => true
  validates :version, :presence => true
  validates :description, :presence => true, :length => {:maximum => 140}
  validates :estimated_time, :presence => true, :numericality => {:less_than_or_equal_to => 600}

  has_many :clusters
  has_many :parameters ,:dependent => :destroy
  has_many :inputs , :dependent => :destroy

  mount_uploader :image, ImageUploader


  def app_info
    name + " (" + version + ")"
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/applications_controller.rb
class ApplicationsController < InheritedResources::Base


  before_filter :authenticate_admin_user!, :only => [:edit,:new, :create, :add_inputs, :add_parameters, :add_one_input, :organize_parameters, :update, :decrease_position_parameter, :increase_position_parameter]



  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # POST /operating_systems
  # POST /operating_systems.json
  def create
    @application = Application.new(params[:application])
    @application.estimated_time = 0
    session[:current_application_id]=@application

    respond_to do |format|
      if @application.save
        puts "Guardo correctamente-------------------------------------"
        format.html { redirect_to add_inputs_path(@application), notice: 'Application was successfully created.' }
        puts "Redirijio------------------------------------------------"
        format.json { render json: @application, status: :created, location: @application}
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_inputs
    puts "Entro a add inputs-----......................."
    @application = Application.find(params[:application_id])
    puts "Hasta aqui llego-----------------------"
    @input = @application.inputs.new
    @directories = Directory.find_all_by_is_public(true)
    @cloud_files = CloudFile.find_all_by_user_id(0)

  end

  def add_parameters
    @application = Application.find(params[:application_id])
    @parameter = @application.parameters.new

  end


  def add_one_input
    @application = Application.find(params[:application_id])
    @input =  Input.find(params[:input_id])
    @input.name =  params[:name]
    puts params
    @input.application_id = @application.id

    if@input.is_directory?
      @directory = Directory.find(@input.value.to_i)
      @input.directory = @directory
      @input.value = 'DIR('+@directory.name+')'

    elsif @input.is_file?
      @cloud_file = CloudFile.find(@input.value.to_i)
      @input.cloud_file = @cloud_file
      @input.value = @cloud_file.name
    end
    respond_to do |format|
      if @input.save
        format.html { redirect_to add_inputs_path(@application), notice: 'Input successfully added.' }
        format.json { render json: @application, status: :created, location: @application}
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end

    redirect_to add_inputs_path(@application)

  end

  def organize_parameters
    @application = Application.find(params[:application_id])


    # si no están ordenados los organiza
    @ordered_inputs = @application.inputs.order('position asc')

    puts 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    i=1
    @ordered_inputs.each do |input|

      puts input.name
      puts input.position


      if input.position==nil or input.position==0 or input.position != i

        input.position = i
        input.save
        puts 'changed'
      end

      puts '--------------------------------------------'

      i=i+1
    end

    @application.save



    @precommand_example =''
    @precommand_base =''
    @precommand_example_names=''



    i=0
    @ordered_inputs.each do |input|
      i=i+1
      @value_example
      @value_base
      @value_example_names
      if input.value == nil || input.value == ''
        @value_example = input.prefix + ' INPUT'+i.to_s
      else
        @value_example = input.prefix + ' ' +input.value
      end

      @value_base = input.prefix + ' INPUT'+i.to_s
      @value_example_names = input.prefix + ' '+ input.name

      @precommand_example = @precommand_example + ' ' + @value_example
      @precommand_base =  @precommand_base + ' ' + @value_base
      @precommand_example_names = @precommand_example_names + ' ' + @value_example_names
    end

    if @application.begin_command == nil
      @application.begin_command=''
    end

    if @application.end_command == nil
      @application.end_command=''
    end

    @application.base_command = @application.begin_command + @precommand_base + ' '+@application.end_command
    @example_command =  @application.begin_command + @precommand_example + ' '+@application.end_command
    @example_command_names = @application.begin_command + @precommand_example_names + ' '+@application.end_command

    @application.save





  end

  def update
    @application = Application.find(params[:id])

    if params[:update_command]

      @new_params = params["application"]

      @begin= @new_params["begin_command"]
      @end= @new_params["end_command"]

      @application.begin_command = @begin
      @application.end_command = @end

      respond_to do |format|
        if @application.save
          format.html { redirect_to organize_parameters_path(@application), notice: 'Application was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @application.errors, status: :unprocessable_entity }
        end
      end

    elsif params[:back]


      respond_to do |format|

        format.html { redirect_to add_inputs_path(@application), notice: '' }
        format.json { render json: @application, status: :created, location: @application}

      end

    elsif params[:finish]

      respond_to do |format|

        format.html { redirect_to @application, notice: '' }
        format.json { render json: @application, status: :created, location: @application}

      end

    else

      respond_to do |format|

        format.html { redirect_to add_inputs_path(@application), notice: 'Update the inputss of your application' }
        format.json { render json: @application, status: :created, location: @application}

      end

    end





  end

  def decrease_position_parameter

    puts 'DECREASE POSITION PARAMETER:'

    @application = Application.find(params[:application_id])
    @input = Input.find(params[:input_id])

    puts 'input actual antes'
    puts @input.name
    puts @input.position



    # si es el primer input no hago nada
    if @input.id != @application.inputs.order('position asc').first.id
      #debo encontrar el input anterior
      @posInputAnterior = @input.position-1

      @inputAnterior = @application.inputs.where('position=?',@posInputAnterior)[0]


      puts 'input anterior antes '
      puts @inputAnterior.name
      puts @inputAnterior.position

      #acá los intercambio
      @input.position =  @input.position-1
      @inputAnterior.position =  @inputAnterior.position+1

      puts 'input actual despues'
      puts @input.name
      puts @input.position

      puts 'input anterior despues '
      puts @inputAnterior.name
      puts @inputAnterior.position

      #acá los grabo
      respond_to do |format|
        if @application.save and   @input.save and @inputAnterior.save
          format.html { redirect_to organize_parameters_path(@application), notice: 'Application was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @application.errors, status: :unprocessable_entity }
        end
      end

    else
      respond_to do |format|
        format.html { redirect_to organize_parameters_path(@application), notice: 'There was an error' }
        format.json { head :no_content }
      end
    end







  end

  def increase_position_parameter

    @application = Application.find(params[:application_id])
    @input = Input.find(params[:input_id])

    # si es el ultimo input no hago nada
    if @input.id != @application.inputs.order('position asc').last.id
      #debo encontrar el input anterior
      @posInputSiguiente = @input.position+1

      @inputSiguiente = @application.inputs.where('position=?',@posInputSiguiente)[0]

      puts 'XXXXXXXXXXXXXXXXXXXXXX'
      puts 'pos input actual'
      puts @input.position
      puts 'pos input anterior'
      puts @posInputSiguiente

      #acá los intercambio
      @input.position =  @input.position+1
      @inputSiguiente.position =  @inputSiguiente.position-1

      #acá los grabo
      respond_to do |format|
        if @application.save and   @input.save and @inputSiguiente.save
          format.html { redirect_to organize_parameters_path(@application), notice: 'Application was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @application.errors, status: :unprocessable_entity }
        end
      end

    else
      respond_to do |format|
        format.html { redirect_to organize_parameters_path(@application), notice: 'There was an error' }
        format.json { head :no_content }
      end
    end






  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_directory=(dir)
    @current_directory = dir
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_apps.html.erb
<div class="row-fluid">
  <ul class="thumbnails">
<% @applications.each do |application| %>




          <li class="span3">
            <div class="thumbnail">
              <%= image_tag 'Instituto_Humboldt_logo.jpg', :size => '300x200', :html=>{:class=>'media-object'}%>
              <div class="caption">
                <h4><%= application.name %> : <%= application.version %></h4>
                <p><%= application.description %></p>
                <p>
                  <%= link_to 'Details', application, :class => "btn btn-primary" %>

                  <% if user_signed_in? %>
                      <%= link_to 'Launch Demo',demo_execution_path(application.id),:id=>'launchButton', :name => "launch", :class => "btn btn-info"%>
                  <% end %>
                </p>
              </div>
            </div>
          </li>



<% end %>
</ul>
</div>

app/views/applications/_form.html.erb
<%= form_for(@application, :html => {:multipart => true})  do |f| %>
    <div class="well" xmlns="http://www.w3.org/1999/html">
    <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, :title => 'Application name.' %>
        </div>


        <div class="field">
          <%= f.label :version %>
          <%= f.text_field :version, :title => 'Application version (ej. 1.0).' %>
        </div>

        <div class="field">
          <%= f.label :installer_url %>
          <%= f.text_field :installer_url, :title => 'URL address where the installation Script is located.' %>
        </div>

        <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, :rows=>'3', :title => 'Small meaningful app description.' %>
         </div>


   <!-- <div class="field">
      <%= f.label "Application Icon" %><br />
      <%= f.file_field :image , :title => 'Application icon'%>
    </div> -->


      <br>

  <div class="actions">
    <%= f.submit  'Next', class: 'btn btn-primary' %>
  </div>
    </div>
<% end %>

app/views/applications/add_inputs.html.erb
<%= form_for(@input) do |f|  %>
    <% if @application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

          <ul>
            <% @application.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

    <% end %>

    <h1> <%= @application.name %>  <%= @application.version %> </h1>
    <br>
    <div class="well">
      <h3>Name </h3>
      <%= @application.name %>
      <h3> Version </h3>
      <%= @application.version %>
      <h3> Installer Url </h3>
      <%= @application.installer_url %>
    </div>
    <br>
    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <h2> Describe the inputs of your application </h2>



    <% if @application.inputs.any? %>

        <br>


        <h3> Current Inputs: </h3>



        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Prefix</th>
            <th>Value</th>
            <th>File</th>
            <th>Directory</th>
            <th></th>
          </tr>
          <% @application.inputs.each do |input| %>
              <tr>
                <td> <%= input.name %></td>
                <td> <%= input.description %></td>
                <td> <%= input.prefix %></td>
                <td> <%= input.value %></td>
                <td><% if input.is_file? %> X <% end %></td>
                <td><% if input.is_directory? %> X <% end %></td>
                <td><%= link_to 'Delete', input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>

          <% end %>
        </table>

    <% end %>




    <h2> Add Input: </h2>
    <div class="well">
      <div class="form-horizontal">

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, :title => 'What is the input name?' %>
        </div>

        <div class="field">
          <%= f.label :is_file, :html=>{:class=>"checkbox inline"} do%>
              <%= f.check_box :is_file , :onclick=>"set_display(this, 'fileButton')"%>
              It's a file?
          <% end %>
        </div>

        <div class="field">

          <%= f.label :is_directory, :html=>{:class=>"checkbox inline"} do%>
              <%= f.check_box :is_directory, :onclick=>"set_display(this, 'directoryButton')" %>
              It's a directory?
          <% end %>
        </div>

        <div class="field">
          <%= f.label :prefix %>
          <%= f.text_field :prefix, :title => 'What character sequence precedes the input value? (ej. -v)' %>
        </div>

        <div class="field" id="textButton">
          <%= f.label :value %>
          <%= f.text_field :value, :title => 'What is the inputs value?' %>
        </div>
          <% i=0 %>
          <div class="field" id="fileButton" style="display: none">
            <%= f.label :value %>
            <%= link_to raw('<i class="icon-file icon-white"></i> Select File') , "#fileModal", :onclick => "set_field('#{(i).to_s}');" ,:class => "btn btn-info", :data => {:toggle => "modal"}, :role => "button" , :id => "but"+(i+1).to_s%>
            <%= label_tag "lab"+(i+1).to_s, "", :id => 'lab'+(i+1).to_s%>
            <%= f.hidden_field :value, :id => 'inputs_'+(i).to_s%>
          </div>


          <div class="field" id="directoryButton" style="display: none">
            <%= f.label :value %>
            <%= link_to raw('<i class="icon-folder-open icon-white"></i> Select Directory') , "#directoryModal", :onclick => "set_field('#{(i).to_s}');" ,:class => "btn btn-success", :data => {:toggle => "modal"}, :role => "button" , :id => "but"+(i+1).to_s%>
            <%= label_tag "lab"+(i+1).to_s, "", :id => 'lab'+(i+1).to_s%>
            <%= f.hidden_field :value, :id => 'inputs_'+(i).to_s%>
          </div>







        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, :rows => 3, :title => 'Add an inputs description.' %>
        </div>

        <div class="field">
          <%= f.hidden_field :application_id , :value => @application.id %>
        </div>




        <div class="actions">
          <%= f.submit "Add Input" %>
        </div>
      </div>
    </div>
    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <div class="actions">
      <%= f.submit 'Next', :name => "next" , class: 'btn btn-primary'%>
    </div>

   <div id="fileModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="fileModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="fileModalLabel">Your Files:</h3>
    </div>
    <div class="well">
      <div class="modal-body">
        <div class="css-treeview">

          <ul class="nav nav-list">
            <%= render :partial => 'browser/treeview', :collection => @directories, :as => :directory %>
            <% @cloud_files.each do |cloud_file| %>
                <li><%= link_to cloud_file.name, '#', :onclick => "set_value('#{cloud_file.id}', '#{cloud_file.name}');", :data => {:dismiss => "modal"}  %></li>
            <% end %>
          </ul>
        </div>

      </div>
    </div>
    </div>


    <div id="directoryModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="directoryModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="directoryModalLabel">Your Directories:</h3>
      </div>
      <div class="well">
        <div class="modal-body">
          <div class="css-treeview">

            <ul class="nav nav-list">
              <%= render :partial => 'browser/treeview_no_files', :collection => @directories, :as => :directory %>
            </ul>
          </div>

        </div>
      </div>
    </div>

<% end %>

app/views/applications/add_parameters.html.erb
<%= form_for(@parameter) do |f| %>
    <% if @application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

          <ul>
            <% @application.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

    <% end %>



    <h1> <%= @application.name %> <%= @application.version %> </h1>
    <h1> Adding inputs </h1>

    <table>
      <tr>
        <td>
          <h3>Name </h3>
        </td>
      </tr>
      <td>
        <%= @application.name %>
      </td>
      </tr>
      <tr>
        <td>
          <h3> Version </h3>
        </td>
      </tr>
      <td>
        <%= @application.version %>
      </td>
      </tr>
      <tr>
        <td>
          <h3> Installer Url </h3>
        </td>
      </tr>
      <td>
        <%= @application.installer_url %>
      </td>
      </tr>
    </table>

    <br>
    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <h2> Inputs: </h2>



    <% if @application.inputs.any? %>

        <br>


        <table class="table">
          <tr>
            <td>Name</td>
            <td>Description</td>
            <td>Prefix</td>
            <td>File</td>
            <td>Directory</td>
          </tr>
          <% @application.inputs.each do |input| %>
              <tr>
                <td> <%= input.name %></td>
                <td> <%= input.description %></td>
                <td> <%= input.prefix %></td>
                <td><% if input.is_file? %> X <% end %></td>
                <td><% if input.is_directory? %> X <% end %></td>

              </tr>
          <% end %>
        </table>

    <% else %>
        <br>
        <h3> No inputs </h3>

    <% end %>


    <br>
    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <h2> Describe parameters of your application </h2>

    <% if @application.parameters.any? %>

        <br>


        <h3> Current Parameters: </h3>



        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Prefix</th>
          </tr>
          <% @application.parameters.each do |param| %>
              <tr>
                <td> <%= param.name %></td>
                <td> <%= param.prefix %></td>
                <td><%= link_to 'Delete', param, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
          <% end %>
        </table>

    <% end %>


    <h2> Add Parameter: </h2>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :prefix %>
      <%= f.text_field :prefix %>
    </div>


    <div class="actions">
      <%= f.submit nil %>
    </div>


    <br>
    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <div class="actions">
      <%= f.submit 'Back', :name => "back" %>
    </div>

    <div class="actions">
      <%= f.submit 'Next', :name => "next" %>
    </div>





<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Available Apps</h1>

 <br>
<br>
<%=  render 'apps' %>

app/views/applications/new.html.erb
<h1>Add a new Application</h1>
<br>

<%= render 'form' %>


<%= link_to 'Back', applications_path %>

app/views/applications/organize_parameters.html.erb
<%= form_for(@application, :html=>{:multipart => true}) do |f| %>
    <% if @application.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

          <ul>
            <% @application.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

    <% end %>

    <h1> <%= @application.name %> <%= @application.version %> </h1>
    <br>
    <div class="well">
      <h3>Name </h3>
      <%= @application.name %>
      <h3> Version </h3>
      <%= @application.version %>
      <h3> Installer Url </h3>
      <%= @application.installer_url %>
    </div>
    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <h2> Organize the Inputs: </h2>



    <% if @application.inputs.any? %>

        <br>


        <table class="table table-striped">
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Prefix</th>
            <th>Value</th>
            <th>File</th>
            <th>Directory</th>
            <th>Position</th>
          </tr>
          <% @application.inputs.order('position asc').each do |input| %>
              <tr>
                <td> <%= input.name %></td>
                <td> <%= input.description %></td>
                <td> <%= input.prefix %></td>
                <td> <%= input.value %></td>
                <td><% if input.is_file? %> X <% end %></td>
                <td><% if input.is_directory? %> X <% end %></td>
                <td> <b> <%= input.position %> </b></td>
                <td> <b><%= link_to '-', decrease_position_parameter_path(@application,input) %></b></td>
                <td> <b><%= link_to '+', increase_position_parameter_path(@application,input) %></b></td>
              </tr>
          <% end %>
        </table>

    <% else %>
        <br>
        <h3> No inputs </h3>

    <% end %>

    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>

    <h2> Base Command: </h2>
    <div class="well">
      <div class="field">
        <%= f.label :begin_command %>
        <%= f.text_field :begin_command %>
      </div>

      <div class="field">
        <%= f.label :end_command %>
        <%= f.text_field :end_command %>
      </div>

      <div class="actions">
        <%= f.submit 'Update Command', :name => "update_command" %>
      </div>

      <br>
      <br>

      <h4>Example:</h4>

      <%= @example_command %>

      <h4>General Command:</h4>

      <%= @example_command_names %>

      <h4>Base Command:</h4>

      <%= @application.base_command %>
    </div>
    <br>

    <ul class="nav nav-list">

      <li class="divider"></li>

    </ul>


    <br>

    Enter a preferred virtual machine size:

    <br>

    <%= select :execution_params, :instance_type , Aws::Ec2::INSTANCE_TYPES %>

    <br>
    <br>

    Enter an estimated time per job in minutes:

    <br>

    <!--<%= number_field :execution_params, :time_per_job %>-->
    <%= select :execution_params, :time_per_job , (1..1440).map { |i| i} %>



    <br>



    <div class="actions">
      <%= f.submit 'Back', :name => "back" %>
    </div>

    <div class="actions">
      <%= f.submit 'Finish', :name => "finish", :class => "btn btn-primary" %>
    </div>




<% end %>

app/views/applications/show.html.erb
<h1> <%= @application.name %>  <%= @application.version %> </h1>
<br>



<h3>Name </h3>
<%= @application.name %>
<h3>Version </h3>
<%= @application.version %>
<h3>Description </h3>
<%= @application.description %>

<br>
<br>

<ul class="nav nav-list">

  <li class="divider"></li>

</ul>

<h2> Inputs: </h2>



<% if @application.inputs.any? %>

    <br>


    <table class="table">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Prefix</th>
        <th>Value</th>
        <th>File</th>
        <th>Directory</th>
        <th>Position</th>
      </tr>
      <% @application.inputs.order('position asc').each do |input| %>
          <tr>
            <td> <%= input.name %></td>
            <td> <%= input.description %></td>
            <td> <%= input.prefix %></td>
            <td> <%= input.value %></td>
            <td><% if input.is_file? %> X <% end %></td>
            <td><% if input.is_directory? %> X <% end %></td>
            <td> <b> <%= input.position %> </b></td>

          </tr>
      <% end %>
    </table>

<% else %>
    <br>
    <h3> No inputs </h3>

<% end %>


<br>
<br>

<ul class="nav nav-list">

  <li class="divider"></li>

</ul>

<h2> Base Command: </h2>



<%= @application.base_command %>

<br>
<br>

<ul class="nav nav-list">

  <li class="divider"></li>

</ul>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_application_path(@application) %> |
    <% end %>
<%= link_to 'Back', applications_path %>