config/routes.rb
ECloudsV01::Application.routes.draw do

  match "executions/costs" => "executions#costs" , :as => "costs"

  resources :executions do
    resources :jobs
  end

  resources :inputs

  resources :parameters

  resources :applications  do
    resources :inputs
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :virtual_machine_events

  resources :directories
  resources :cloud_files
  resources :instance_types
  resources :operating_systems
  resources :virtual_machines
  resources :clusters  do
    resources :virtual_machines
    member do
      post :add_virtual_machines
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :sessions => "sessions"}

  devise_scope :user do
    delete "users/sign_out"  => "devise/session#destroy"
  end

  root :to => "static_pages#home"

  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  get "browser/index"
  get "executions/costs"

  match "browse/index" => "browser#index" , :as =>  "data_home"

  match "browse/:directory_id" => "browser#browse", :as => "browse"
  match "browse/:directory_id/new_folder" => "directories#new", :as => "new_sub_directory"

  match "browse/:directory_id/new_file" => "cloud_files#new", :as => "new_sub_file"

  match "browse/:directory_id/rename" => "directories#edit", :as => "rename_directory"

  match "virtual_machines/:virtual_machine_id/stop/:current_cluster_id"  => "virtual_machines#stop", :as => "stop_virtual_machine"
  match "virtual_machines/:virtual_machine_id/start/:current_cluster_id"  => "virtual_machines#start", :as => "start_virtual_machine"
  match "virtual_machines/:virtual_machine_id/reboot/:current_cluster_id"  => "virtual_machines#reboot", :as => "reboot_virtual_machine"
  match "virtual_machines/:virtual_machine_id/terminate/:current_cluster_id"  => "virtual_machines#terminate", :as => "terminate_virtual_machine"

  match "virtual_machines/start_all/:current_cluster_id"  => "virtual_machines#start_all", :as => "start_all_virtual_machine"
  match "virtual_machines/reboot_all/:current_cluster_id"  => "virtual_machines#reboot_all", :as => "reboot_all_virtual_machine"
  match "virtual_machines/stop_all/:current_cluster_id"  => "virtual_machines#stop_all", :as => "stop_all_virtual_machine"
  match "virtual_machines/terminate_all/:current_cluster_id"  => "virtual_machines#terminate_all", :as => "terminate_all_virtual_machine"

  match "add_inputs/:application_id/" => "applications#add_inputs", :as => "add_inputs"
  match "organize_parameters/:application_id/" => "applications#organize_parameters", :as => "organize_parameters"
  match "decrease_position/:application_id/:input_id" => "applications#decrease_position_parameter" , :as => "decrease_position_parameter"
  match "increase_position/:application_id/:input_id" => "applications#increase_position_parameter" , :as => "increase_position_parameter"

  match "define_execution/:execution_id" => "executions#define_execution" , :as => "define_execution"
  match "define_execution_part2/:execution_id" => "executions#define_execution_part2" , :as => "define_execution_part2"
  match "launch_executions/:id" => "executions#launch_execution" , :as => "launch_execution"
  match "demo_executions/:application_id" => "executions#demo_execution" , :as => "demo_execution"

end

app/controllers/browser_controller.rb
class BrowserController < ApplicationController

  #this action is for viewing folders
  def browse

    #esto es para crear un nuevo archivo desde el modal
    @cloud_file = CloudFile.new


    if params[:directory_id] #if we want to upload a file inside another folder
      @current_directory = current_user.directories.find(params[:directory_id])
      @cloud_file.directory_id = @current_directory.id
    end

    #acá guardo el current dir en la sessión
     session[:current_dir_session]  = @current_directory


    #get the folders owned/created by the current_user
    @current_directory = current_user.directories.find(params[:directory_id])

    if @current_directory

      #getting the folders which are inside this @current_folder
      @directories = @current_directory.children

      #We need to fix this to show files under a specific folder if we are viewing that folder
      @cloud_files =  @current_directory.cloud_files

      render :action => "index"
    else
      flash[:error] = "Don't be cheeky! Mind your own folders!"
      redirect_to root_url
    end
  end

  def index
    #esto es para crear un nuevo archivo desde el modal
    @cloud_file = CloudFile.new


    if params[:directory_id] #if we want to upload a file inside another folder
      @current_directory = current_user.directories.find(params[:directory_id])
      @cloud_file.directory_id = @current_directory.id
    end

    session[:current_dir_session] = nil

    if user_signed_in?
      #show only root folders (which have no parent folders)
      @directories = current_user.directories.roots

      #show only root files which has no "folder_id"
      @cloud_files = current_user.cloud_files.where("directory_id is NULL")
    end
  end


end

app/helpers/browser_helper.rb
module BrowserHelper
end

app/views/browser/_breadcrumbs.html.erb
<div  class ="breadcrumb">
  <div class="divider" >
  <% if @current_directory #checking if we are under any folder %>
     <%= link_to "/", data_home_path %>
      <% @current_directory.ancestors.reverse.each do |directory| %>
           <%= link_to directory.name, browse_path(directory) %>  /
      <% end %>

        <%= @current_directory.name %>


  <% else #if we are not under any folder%>
        <%= link_to "/", data_home_path %>

      </div>
  <% end %>

</div>

app/views/browser/_treeview.html.erb
<ul class="nav nav-list">
  <li><input type="checkbox" id="item-0" /><label for="item-0"><%= directory.name %> </label>
      <ul class="nav nav-list">
      <% unless directory.children.empty? %>
          <%= render :partial => 'browser/treeview', :collection => directory.children, :as => :directory %>
      <% end %>

      <% directory.cloud_files.each do |cloud_file| %>
            <li><%= link_to cloud_file.name, '#', :onclick => "set_value('#{cloud_file.id}', '#{cloud_file.name}');", :data => {:dismiss => "modal"}  %></li>
      <% end %>
      </ul>
  </li>
  </ul>

app/views/browser/_treeview_no_files.html.erb
<ul class="nav nav-list">
  <li>
    <input type="checkbox" id="item-0" /><label for="item-0" data-dismiss="modal" onclick="set_value('<%= directory.id %>', '<%= directory.name %>');"><%= directory.name %> </label>
      <ul class="nav nav-list">
      <% unless directory.children.empty? %>
          <%= render :partial => 'browser/treeview_no_files', :collection => directory.children, :as => :directory %>
      <% end %>

      </ul>
  </li>
  </ul>

app/views/browser/browse.html.erb
<table class= "table ">

  <tr>
    <td>
      <h2>My Data</h2>
    </td>
    <td>
      <!-- Button to trigger modal -->
      <a href="#myModal" role="button" class="btn" data-toggle="modal">Upload File</a>
      <a href="#modalCreateDir" role="button" class="btn" data-toggle="modal">Create Directory</a>
      <!--<%= link_to 'New Cloud file', new_cloud_file_path %>-->
    </td>
  </tr>

</table>

<div class="label label-info"><%= session[:current_directory].directory_path %></div>

<!-- New Directory -->

<% if @current_directory %>
    <li><%= link_to "New Folder", new_sub_directory_path(@current_directory ) %></li>
<% else %>
    <li><%= link_to "New Folder", new_directory_path %></li>
<% end %>

<!-- Listing Directories -->

<h2>Directories</h2>

<table class= "table table-striped">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @directories.each do |directory| %>
      <tr>
        <td><%= link_to directory.name, browse_path(directory) %></td>
        <td><%= directory.directory_path %></td>
        <td>---</td>
        <td><%= link_to 'Show', directory %></td>
        <!--<td><= link_to 'Edit', edit_cloud_file_path(cloud_file) %></td>-->
        <!-- <td><= link_to 'Destroy', cloud_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>  -- >
      </tr>
  <% end %>
</table>

<!-- Files -->

<% @cloud_files.each do |cloud_file| %>
    <tr>
      <td><li class="icon-file"></td>
      <td><%= cloud_file.name %></td>
      <td><%= number_to_human_size(cloud_file.size) %></td>
      <td><a href="<%= cloud_file.complete_url %>">Download</a></td>
      <td><%= link_to "Delete" , cloud_file, :confirm => 'Are you sure?', :method => :delete%></td>

    </tr>
<% end %>

<!-- modal para rear directorio -->

<br />




<!-- modal para subir archivo-->

<!-- Modal -->
<div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"data-show="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Upload File</h3>
  </div>
  <div class="modal-body">
    <p>
      <%= form_for(@cloud_file, :html => {:multipart =>true}) do |f| %>
          <% if @cloud_file.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@cloud_file.errors.count, "error") %> prohibited this cloud_file from being saved:</h2>

              <ul>
                <% @cloud_file.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>




        <div class="field">
          <%= f.label "file" %><br />
          <%= f.file_field :avatar %>
        </div>




        </p>
        </div>
        <div class="modal-footer">

          <div class="actions">
            <%= f.submit %>
          </div>
          <button class="btn btn-primary">Save changes</button>
        </div>

    <% end %>
    </div>

<!-- FIN de modal para subir archivo-->



<!-- modal para crear directorio-->

<!-- Modal -->
<div class="modal hide fade" id="modalCreateDir" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-show="false">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="modalCreateDirlLabel">Create Directory</h3>
  </div>
  <div class="modal-body">
    <p>

  </div>

</div>

<!-- FIN de modal para create directory-->

app/views/browser/index.html.erb
<h1>My Data</h1>


<!-- Button to trigger modal -->
<!--<a href="#myModal" role="button" class="btn" data-toggle="modal">Upload File</a> -->

<!-- TO create folders and directories -->
<ul >
  <% if @current_directory %>

      <ul class="pager">
        <li class="next"><%= link_to "Upload", new_sub_file_path(@current_directory), :class=>'btn btn-primary' %></li>
        <li class="next"><%= link_to "New Folder", new_sub_directory_path(@current_directory), :class=>'btn btn-primary' %></li></ul>
  <% else %>
      <ul class="pager">
        <li class="next"><%= link_to "Upload", new_cloud_file_path, :class=>'btn btn-primary' %></li>
        <li class="next"><%= link_to "New Folder", new_directory_path, :class=>'btn btn-primary' %></li></ul>
  <% end %>
</ul>

<%= render :partial => "browser/breadcrumbs" %>

<!-- Directories -->


<table class= "table table-hover">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Size (bytes)</th>
    <th>Last modified</th>
    <th></th>
    <th></th>
  </tr>

  <% @directories.each do |directory| %>
      <tr >
        <td> <i class="icon-folder-open"></i></td>
        <td ><%= link_to directory.name, browse_path(directory) %></td>
        <td></td>
        <td><%= directory.updated_at %></td>
        <td>
          <%= link_to "Rename" , rename_directory_path(directory) %>
        </td>

        <td>
          <%= link_to "Delete", directory, :confirm => 'Are you sure to delete the folder and all of its contents?', :method => :delete %>
        </td>

      </tr>
  <% end %>


  <!-- Files -->

  <% @cloud_files.each do |cloud_file| %>
      <tr>
        <td><li class="icon-file"></td>
        <td><%= cloud_file.name %></td>
        <td><%= number_to_human_size cloud_file.size %></td>
        <td><a href="<%= cloud_file.complete_url %>">Download</a></td>
        <td><%= link_to "Delete" , cloud_file, :confirm => 'Are you sure?', :method => :delete%></td>

      </tr>
  <% end %>



</table>




<!-- //////////////////////////////////////////////////////////////////////////////////////////////-->

<!-- Modals -->

<!-- modal para subir archivo-->

<!-- Modal -->
<div class="modal hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-show="true" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Upload File</h3>
  </div>
  <div class="modal-body">
    <p>
      <%= form_for(@cloud_file, :html => {:multipart =>true}) do |f| %>
          <% if @cloud_file.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@cloud_file.errors.count, "error") %> prohibited this cloud_file from being saved:</h2>

              <ul>
                <% @cloud_file.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>




        <div class="field">
          <%= f.label "file" %><br />
          <%= f.file_field :avatar %>
        </div>




        </p>
        </div>
        <div class="modal-footer">

          <div class="btn ">
            <%= f.submit %>
          </div>

        </div>

    <% end %>
    </div>

<!-- FIN de modal para subir archivo-->